### ISSUE TITLE
Update Docker Hub README: dockercmd.sh not found

### ISSUE THREAD

**Issue by rpherrera** [blang/latex-docker#19]
In https://hub.docker.com/r/blang/latex/ we can see that in README it suggests us to download `dockercmd.sh`, which has been replaced by `latexdockercmd.sh`:

The following statement is not working anymore:
```
wget https://raw.githubusercontent.com/blang/latex-docker/master/dockercmd.sh
--2018-04-08 00:47:14--  https://raw.githubusercontent.com/blang/latex-docker/master/dockercmd.sh
Resolving raw.githubusercontent.com... 151.101.92.133
Connecting to raw.githubusercontent.com|151.101.92.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-08 00:47:14 ERROR 404: Not Found.
```

So please replace according to the most recent README version, which can be found in this repository.

**Comment by blang** [comment]
Thanks! I fixed it
