### ISSUE TITLE
`exec` seems unecessary

### ISSUE THREAD

**Issue by startakovsky** [blang/latex-docker#30]
In `latexdockercmd.sh` it seems `exec` in the line below, when removed, still works just fine. Why is it necessary?

Thanks,
Steven

https://github.com/blang/latex-docker/blob/42d2c532a09a00938331512fd2b539f9944c400c/latexdockercmd.sh#L3

**Comment by blang** [comment]
It replaces the shell process instead of forking. This comes in handy so you don't need to manage exit codes and signals. Please see https://mywiki.wooledge.org/WrapperScript for reference

**Comment by startakovsky** [comment]
Thanks Benedikt! Very helpful.
