### ISSUE TITLE
biber missing

### ISSUE THREAD

**Issue by janstuemmel** [blang/latex-docker#5]
the biber backend for biblatex is missing, i think such an essential part of latex has to be included in the container.

i use your image for automated builds. i think your image is really popular, because gitlab.com suggests it for gitlab-ci. but always execute `apt-get update && apt-get install -y XY` before build decelerates build time heavily for such an easy task...

**Comment by blang** [comment]
Basically this image is a blueprint/base for your own creations.
Have a look at [latex-docker-advanced](https://github.com/blang/latex-docker-advanced) for example.
If i have time, i will create a better image with more tools included

**Comment by janstuemmel** [comment]
ok, made my own and inherited from yours...

thx
